In [ ]:
import torch
torch.__version__

'2.6.0+cu124'

# SCALAR

In [ ]:
scalar = torch.tensor(6)
scalar

tensor(6)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.shape

torch.Size([])

In [ ]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

6

# VECTOR

In [ ]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
# Check the number of dimensions of vector
vector.ndim

1

In [ ]:
# Check shape of vector
vector.shape

torch.Size([2])

# MATRIX

In [ ]:
matrix = torch.tensor([[2,2],
                       [3,3],
                       [4,4]])
matrix

tensor([[2, 2],
        [3, 3],
        [4, 4]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix.shape

torch.Size([3, 2])

# TENSOR

In [ ]:
tensor = torch.tensor([[[1,2,3],
                        [3,4,5],
                        [5,6,7]]])
tensor

tensor([[[1, 2, 3],
         [3, 4, 5],
         [5, 6, 7]]])

In [ ]:
tensor.ndim

3

In [ ]:
tensor.shape

torch.Size([1, 3, 3])

# Random Tensors

When building machine learning models with PyTorch, it's rare you'll create tensors by hand (like what we've been doing).
Instead, a machine learning model often starts out with large random tensors of numbers and adjusts these random numbers as it works through data to better represent it.

*Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...*

In [ ]:
random_tensor = torch.rand(size=(3,4))
random_tensor

tensor([[0.1829, 0.7932, 0.2424, 0.0659],
        [0.7030, 0.4313, 0.1945, 0.9932],
        [0.4014, 0.2990, 0.5526, 0.5381]])

The flexibility of torch.rand() is that we can adjust the size to be whatever we want.

For example, say you wanted a random tensor in the common image shape of [224, 224, 3] ([height, width, color_channels]).


In [ ]:
random_image_size_tensor = torch.rand(size = (224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

Create tensor with all zeros

In [ ]:
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Create tensor with all ones

In [ ]:
one = torch.ones(size=(3,4))
one, one.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [ ]:
range = torch.range(0,10)
range

<ipython-input-19-91a60021e470>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  range = torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
zero_to_ten = torch.arange(start = 0, end = 10, step = 1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Getting Information From Tensor

Once you've created tensors (or someone else or a PyTorch module has created them for you), you might want to get some information from them.

We've seen these before but three of the most common attributes you'll want to find out about tensors are:

    shape - what shape is the tensor? (some operations require specific shape rules)
    dtype - what datatype are the elements within the tensor stored in?
    device - what device is the tensor stored on? (usually GPU or CPU)

Let's create a random tensor and find out details about it.

In [ ]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.6499, 0.9459, 0.9203, 0.9694],
        [0.6182, 0.8580, 0.5276, 0.9463],
        [0.3025, 0.8458, 0.9679, 0.8027]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu
