In [322]:
import torch
torch.__version__

'2.6.0+cu124'

# SCALAR

In [323]:
scalar = torch.tensor(6)
scalar

tensor(6)

In [324]:
scalar.ndim

0

In [325]:
scalar.shape

torch.Size([])

In [326]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

6

# VECTOR

In [327]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [328]:
# Check the number of dimensions of vector
vector.ndim

1

In [329]:
# Check shape of vector
vector.shape

torch.Size([2])

# MATRIX

In [330]:
matrix = torch.tensor([[2,2],
                       [3,3],
                       [4,4]])
matrix

tensor([[2, 2],
        [3, 3],
        [4, 4]])

In [331]:
matrix.ndim

2

In [332]:
matrix.shape

torch.Size([3, 2])

# TENSOR

In [333]:
tensor = torch.tensor([[[1,2,3],
                        [3,4,5],
                        [5,6,7]]])
tensor

tensor([[[1, 2, 3],
         [3, 4, 5],
         [5, 6, 7]]])

In [334]:
tensor.ndim

3

In [335]:
tensor.shape

torch.Size([1, 3, 3])

# Random Tensors

When building machine learning models with PyTorch, it's rare you'll create tensors by hand (like what we've been doing).
Instead, a machine learning model often starts out with large random tensors of numbers and adjusts these random numbers as it works through data to better represent it.

*Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...*

In [336]:
random_tensor = torch.rand(size=(3,4))
random_tensor

tensor([[0.5856, 0.6219, 0.1670, 0.0690],
        [0.7687, 0.0796, 0.5630, 0.7562],
        [0.9144, 0.5953, 0.1598, 0.7942]])

The flexibility of torch.rand() is that we can adjust the size to be whatever we want.

For example, say you wanted a random tensor in the common image shape of [224, 224, 3] ([height, width, color_channels]).


In [337]:
random_image_size_tensor = torch.rand(size = (224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

Create tensor with all zeros

In [338]:
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Create tensor with all ones

In [339]:
one = torch.ones(size=(3,4))
one, one.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [340]:
range = torch.range(0,10)
range

<ipython-input-340-91a60021e470>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  range = torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [341]:
zero_to_ten = torch.arange(start = 0, end = 10, step = 1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Getting Information From Tensor

Once you've created tensors (or someone else or a PyTorch module has created them for you), you might want to get some information from them.

We've seen these before but three of the most common attributes you'll want to find out about tensors are:

    shape - what shape is the tensor? (some operations require specific shape rules)
    dtype - what datatype are the elements within the tensor stored in?
    device - what device is the tensor stored on? (usually GPU or CPU)

Let's create a random tensor and find out details about it.

In [342]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.8265, 0.5011, 0.8666, 0.6563],
        [0.6172, 0.4579, 0.0037, 0.2373],
        [0.7310, 0.9526, 0.6387, 0.4777]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# Manipulating Tensors


    Addition
    Substraction
    Multiplication (element-wise)
    Division
    Matrix multiplication

In [343]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [344]:
tensor * 10

tensor([10, 20, 30])

In [345]:
tensor = tensor + 5

In [346]:
tensor - 10

tensor([-4, -3, -2])

In [347]:
tensor = torch.multiply(tensor, 10)

In [348]:
tensor

tensor([60, 70, 80])

# Matrix multiplication

"@" in Python is the symbol for matrix multiplication.

In [349]:
tensor = torch.tensor([1,2,3])

In [350]:
tensor * tensor

tensor([1, 4, 9])

In [351]:
torch.matmul(tensor, tensor)

tensor(14)

In [352]:
# matmul is preferred over '@' for Matrix multiplication
tensor @ tensor

tensor(14)


**One of the most common errors in deep learning (shape errors)**

Because much of deep learning is multiplying and performing operations on matrices and matrices have a strict rule about what shapes and sizes can be combined, one of the most common errors you'll run into in deep learning is shape mismatches.

In [353]:
tensorA = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensorB = torch.tensor([[7,8],
                        [9,0],
                        [1,2]])
#tensorC = torch.matmul(tensorA, tensorB) #This gives error

In [354]:
tensorD = torch.tensor([[1,2,3],
                        [4,5,6]])
tensorE = torch.matmul(tensorA, tensorD)
tensorE

tensor([[ 9, 12, 15],
        [19, 26, 33],
        [29, 40, 51]])

In [355]:
tensor_a = torch.rand(2,3)
tensor_a

tensor([[0.6343, 0.3607, 0.3563],
        [0.3540, 0.4220, 0.4293]])

In [356]:
tensor_b = torch.rand(3,2)
tensor_b

tensor([[0.1776, 0.5659],
        [0.3741, 0.9351],
        [0.2308, 0.6078]])

In [357]:
tensor_c = torch.matmul(tensor_a, tensor_b) # Matmul of 2*3 and 3*2 matrices gives 2*2 matrix
tensor_c

tensor([[0.3298, 0.9128],
        [0.3198, 0.8559]])

In [358]:
tensor_d = torch.matmul(tensor_b, tensor_a)# Matmul of 3*2 and 2*3 matrices gives 3*3 matrix
tensor_d

tensor([[0.3130, 0.3029, 0.3063],
        [0.5683, 0.5295, 0.5348],
        [0.3616, 0.3397, 0.3432]])

In [359]:
#Transpose of a matrix
tensor_b.T

tensor([[0.1776, 0.3741, 0.2308],
        [0.5659, 0.9351, 0.6078]])

In [360]:
#Use torch.mm() for matrix multiplication
tensor_e = torch.mm(tensor_a.T, tensor_b.T)
tensor_e

tensor([[0.3130, 0.5683, 0.3616],
        [0.3029, 0.5295, 0.3397],
        [0.3063, 0.5348, 0.3432]])

In [361]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [362]:
x.max()

tensor(90)

In [363]:
x.min()

tensor(0)

In [364]:
# x.mean() #This gives error as type is not defined as float32
mean = x.type(torch.float32).mean()
mean

tensor(45.)

In [365]:
x.sum()

tensor(450)

In [366]:
mean = mean.type(torch.int8)
mean

tensor(45, dtype=torch.int8)

In [367]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


# Reshaping, stacking, squeezing and unsqueezing
Often times you'll want to reshape or change the dimensions of your tensors without actually changing the values inside them.


1.   torch.reshape(input, shape) -> Reshapes input to shape (if compatible), can also use torch.Tensor.reshape().
2.   Tensor.view(shape) ->	Returns a view of the original tensor in a different shape but shares the same data as the original tensor.
3.   torch.stack(tensors, dim=0) -> Concatenates a sequence of tensors along a new dimension (dim), all tensors must be same size.
4.   torch.squeeze(input) -> Squeezes input to remove all the dimenions with value 1.
5.   torch.unsqueeze(input, dim) ->	Returns input with a dimension value of 1 added at dim.
6.   torch.permute(input, dims) ->	Returns a view of the original input with its dimensions permuted (rearranged) to dims.


In [368]:
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [369]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [370]:
# Change view (keeps same data as original but changes view)
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [371]:
# So changing the view changes the original tensor too.
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [372]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # dim=1 stacks sideways
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])



How about removing all single dimensions from a tensor?

To do so you can use torch.squeeze() (I remember this as squeezing the tensor to only have dimensions over 1).


In [373]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


And to do the reverse of torch.squeeze() you can use torch.unsqueeze() to add a dimension value of 1 at a specific index.

In [374]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


In [375]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


# Indexing (selecting data from tensors)

In [376]:
# Create a tensor
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

Indexing values goes outer dimension -> inner dimension (check out the square brackets).

In [377]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}")
print(f"Second square bracket:{x[0][1]}")
print(f"Third square bracket:{x[0][1][2]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket:tensor([4, 5, 6])
Third square bracket:6


We can also navigate as follows;

x[<0th dim>,<1st dim>,<2nd dim>]


In [378]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [379]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [380]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [381]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

# PyTorch tensors & NumPy

In [382]:
# NumPy array to tensor
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [387]:
# Tensor to NumPy array
tensor = torch.ones(6) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1.], dtype=float32))

In [385]:
# Change the tensor, keep the array the same
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1.], dtype=float32))

# Reproducibility (trying to take the random out of random)

start with random numbers -> tensor operations -> try to make better (again and again and again)

Although randomness is nice and powerful, sometimes you'd like there to be a little less randomness.

Why?

So you can perform repeatable experiments.

For example, you create an algorithm capable of achieving X performance.

And then your friend tries it out to verify you're not crazy.

How could they do such a thing?

That's where reproducibility comes in.

In other words, can you get the same (or very similar) results on your computer running the same code as I get on mine?

Let's see a brief example of reproducibility in PyTorch.

We'll start by creating two random tensors, since they're random, you'd expect them to be different right?

In [390]:
rand_A = torch.rand(3,3)
rand_B = torch.rand(3,3)
print(rand_A)
print(rand_B)
print(rand_A == rand_B)

tensor([[0.8783, 0.4521, 0.7935],
        [0.2753, 0.6973, 0.4124],
        [0.9730, 0.7193, 0.6380]])
tensor([[0.8024, 0.1375, 0.6287],
        [0.6532, 0.1961, 0.3778],
        [0.2169, 0.1126, 0.9201]])
tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])


In [391]:
import random

In [403]:
RANDOM_SEED = 40 # When seed changes, result of the rand will be different)
torch.manual_seed(seed = RANDOM_SEED)
rand_C = torch.rand(3,4)
torch.random.manual_seed(seed = RANDOM_SEED) # Need to repeat the initialization to get same result
rand_D = torch.rand(3,4)
print(rand_C)
print(rand_D)
print(rand_C == rand_D)

tensor([[0.3679, 0.8661, 0.1737, 0.7157],
        [0.8649, 0.4878, 0.5501, 0.1318],
        [0.2897, 0.0707, 0.8016, 0.3244]])
tensor([[0.3679, 0.8661, 0.1737, 0.7157],
        [0.8649, 0.4878, 0.5501, 0.1318],
        [0.2897, 0.0707, 0.8016, 0.3244]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [405]:
torch.cuda.is_available()

False

In [407]:
torch.cpu.device_count()

1